spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ssm_crud
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/sql-mapper/*.xml

# 在控制台输出 SQL 语句  
logging:
  level:
    com.jas.mapper: debug
